### ISSUE TITLE
Stage 401 JWT token error when trying to add Sinopia localAdminMetadata

### ISSUE THREAD

**Issue by jermnelson** [LD4P/ils-middleware#136]
On stage `update_sinopia.sinopia-new-metadata` is throwing the following error:

```python
[2021-12-04, 15:19:46 ] {local_metadata.py:156} ERROR - Failed to add localAdminMetadata, 401
[{"title":"Unauthorized","details":"secret or public key must be provided","status":"401"}]
[2021-12-04, 15:19:46 ] {taskinstance.py:1703} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1332, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1458, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1514, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 151, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 162, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/ils_middleware/tasks/sinopia/local_metadata.py", line 157, in new_local_admin_metadata
    raise Exception(msg)
Exception: Failed to add localAdminMetadata, 401
[{"title":"Unauthorized","details":"secret or public key must be provided","status":"401"}]```

**Comment by jcoyne** [comment]
@jermnelson when does this happen? Intermittently or all the time? Where do you think this 401 error originates from? It's formatted like the sinopia_api errors, but I don't see any messages like "secret or public key must be provided" in sinopia_api?

**Comment by jermnelson** [comment]
This error is happening every time the task is run. In the Stanford DAG, we're generating the JWT in the `update_sinopia.sinopia_login` https://github.com/LD4P/ils-middleware/blob/a42c3b3998897448d4bbc86fbb3cb884383a87aa/ils_middleware/dags/stanford.py#L183-L190 and persisting it to the XCOM. 

This is weird error in testing locally against our Stage Sinopia environments doesn't generate the error. Based on my initial investigation, I think something is incorrect with the settings being sent to Airflow either in TF or through the UI (both sources did look correct from an initial scan)
